export function validateQuestion(q){if(!q||typeof q.text!=='string'||q.text.trim().length<3||q.text.length>1000||!Array.isArray(q.options)||q.options.length!==4||q.options.some(o=>typeof o!=='string'||!o.trim()||o.length>300)||!Number.isInteger(q.correct)||q.correct<0||q.correct>3)return {error:'Enter a question, four nonempty choices, and its correct answer'};return {value:{text:q.text.trim(),options:q.options.map(o=>o.trim()),correct:q.correct}}}
export function validateConfig(c){let duration=Number(c?.durationMinutes),limit=Number(c?.maxViolations);if(!c||!Number.isInteger(duration)||duration<1||duration>240||!Number.isInteger(limit)||limit<1||limit>10||typeof c.title!=='string'||!c.title.trim()||c.title.length>100)return {error:'Set a title, duration 1-240 minutes and violation limit 1-10'};return {value:{title:c.title.trim(),durationMinutes:duration,maxViolations:limit}}}
export function normalizeIdentity(a){let collegeId=String(a?.collegeId||'').trim(),name=String(a?.name||'').trim(),roll=String(a?.roll||'').trim().toUpperCase();if(!/^[\p{L}\p{N} ._\-/]{2,80}$/u.test(collegeId)||!/^[\p{L} .'-]{2,100}$/u.test(name)||!/^[A-Z0-9\-_/]{2,50}$/.test(roll))return {error:'Check college ID, name, and university roll number'};return {value:{collegeId,name,roll}}}
export function deadlineFor(start,e){return new Date(start.getTime()+e.durationMinutes*60_000)}
export function allowedWindow(e,now){return Boolean(e.open)}
export function grade(questions,answers){return questions.reduce((score,q)=>score+(answers[q.questionId]===q.correct?1:0),0)}
export function safeCsvCell(value){let text=String(value??'');if(/^[\s]*[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"'}

export function parseRoster(text){if(typeof text!=='string'||text.length>15000)return {error:'Roster too large'};let rows=text.trim()?text.trim().split(/\r?\n/):[];if(rows.length>60)return {error:'Maximum 60 roster entries'};let out=[],seen=new Set();for(let line of rows){let fields=line.split(',').map(x=>x.trim());if(fields.length!==2||!/[\p{L}\p{N}]/u.test(fields[0])||!/^[-A-Za-z0-9_/]{2,50}$/.test(fields[1])||fields[0].length>80)return {error:'Use one college ID,roll number pair per line'};let [collegeId,roll]=fields;roll=roll.toUpperCase();if(seen.has(roll))return {error:'Duplicate roll number in roster'};seen.add(roll);out.push({collegeId,roll})}return {value:out}}
