import express from 'express';
import mongoose from 'mongoose';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import { rateLimit } from 'express-rate-limit';
import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { deadlineFor, normalizeIdentity, validateConfig, validateQuestion, safeCsvCell, grade, allowedWindow, parseRoster, domainAllows } from './logic.js';

const required = ['ADMIN_PASSWORD','SESSION_SECRET','PUBLIC_ORIGIN'];
if (required.some(k => !process.env[k]) || (!process.env.MONGODB_URI && !process.env.MONGODB_PASSWORD) || (process.env.SESSION_SECRET || '').length < 32) {
  console.error('Missing required configuration or SESSION_SECRET shorter than 32 characters'); process.exit(1);
}
const ORIGIN = process.env.PUBLIC_ORIGIN.replace(/\/$/,'');
if (!/^https:\/\/[^/]+$/.test(ORIGIN) && process.env.NODE_ENV === 'production') throw Error('PUBLIC_ORIGIN must be an HTTPS origin');
const mongoUri=process.env.MONGODB_URI || `mongodb+srv://OneTimeExamApp:${encodeURIComponent(process.env.MONGODB_PASSWORD)}@cluster0.deiixmu.mongodb.net/onetimeexam?retryWrites=true&w=majority&appName=OneTimeExam`;
await mongoose.connect(mongoUri, {serverSelectionTimeoutMS:10000});
const Question = mongoose.model('Question', new mongoose.Schema({text:{type:String,required:true},options:{type:[String],required:true},correct:{type:Number,required:true}}, {timestamps:true}));
const Exam = mongoose.model('Exam', new mongoose.Schema({key:{type:String,unique:true,default:'one'},title:String,durationMinutes:Number,maxViolations:Number,open:Boolean,admitted:{type:Number,default:0},allowedDomains:{type:[String],default:[]},roster:[{collegeId:String,roll:String}]}, {timestamps:true}));
const Attempt = mongoose.model('Attempt', new mongoose.Schema({collegeId:{type:String,required:true},name:{type:String,required:true},roll:{type:String,required:true,unique:true},tokenHash:{type:String,required:true},startedAt:Date,deadlineAt:Date,submittedAt:Date,submitReason:String,answers:{type:Map,of:Number,default:{}},questionSnapshot:[{questionId:String,text:String,options:[String],correct:Number}],violations:[{kind:String,at:Date}],score:Number}, {timestamps:true}));
const app = express(); app.set('trust proxy',1); app.disable('x-powered-by'); app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'"],imgSrc:["'self'",'data:'],connectSrc:["'self'"],objectSrc:["'none'"],frameAncestors:["'none'"]}}})); app.use(express.json({limit:'25kb'})); app.use(cookieParser());
const baseDir = path.dirname(fileURLToPath(import.meta.url));
const limiter = rateLimit({windowMs:15*60*1000,limit:6000,standardHeaders:'draft-8',legacyHeaders:false}); app.use('/api',limiter);
const authLimit = rateLimit({windowMs:15*60*1000,limit:8,standardHeaders:'draft-8',legacyHeaders:false,skipSuccessfulRequests:true});const joinLimit=rateLimit({windowMs:15*60*1000,limit:150,standardHeaders:'draft-8',legacyHeaders:false,skipSuccessfulRequests:true});
function hash(t){return createHmac('sha256',process.env.SESSION_SECRET).update(t).digest('hex')}
function equal(a,b){const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length && timingSafeEqual(x,y)}
function cookie(name,value,maxAge){return {httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge}}
function sign(value){return `${value}.${hash(value)}`}
function verify(value){if(!value || typeof value!=='string') return '';const p=value.lastIndexOf('.');if(p<0)return '';const [v,h]=[value.slice(0,p),value.slice(p+1)];return equal(hash(v),h)?v:''}
function fail(res,status,message){return res.status(status).json({error:message})}
function csrf(req,res,next){if(!['GET','HEAD','OPTIONS'].includes(req.method) && (req.get('origin')!==ORIGIN || req.get('x-exam-request')!=='1')) return fail(res,403,'Request origin rejected');next()};app.use('/api',csrf);
function admin(req,res,next){let session=verify(req.cookies.exam_admin); if(!session)return fail(res,401,'Admin sign-in required');let [exp]=session.split(':');if(!Number(exp)||Date.now()>Number(exp))return fail(res,401,'Admin session expired');next()}
async function student(req,res,next){let token=verify(req.cookies.exam_student);if(!token)return fail(res,401,'Student session required');let a=await Attempt.findOne({tokenHash:hash(token)});if(!a)return fail(res,401,'Student session invalid');req.attempt=a;next()}
async function config(){return await Exam.findOne({key:'one'})}
async function finalize(a,reason){if(a.submittedAt)return a;let answers=a.answers instanceof Map?Object.fromEntries(a.answers):Object.fromEntries(Object.entries(a.answers||{}));let score=grade(a.questionSnapshot,answers); await Attempt.updateOne({_id:a._id,submittedAt:null},{$set:{submittedAt:new Date(),submitReason:reason,score}});return Attempt.findById(a._id)}
async function finalizeExpired(){let pending=await Attempt.find({submittedAt:null,deadlineAt:{$lte:new Date()}}).limit(100);for(let a of pending)await finalize(a,'time')}
async function currentAttempt(a){if(!a.submittedAt && Date.now()>=a.deadlineAt.getTime())return finalize(a,'time');return a}
app.get('/api/public',async(req,res)=>{let e=await config();res.json({title:e?.title||'Online exam',durationMinutes:e?.durationMinutes||null,open:Boolean(e?.open),serverNow:new Date()})});
app.post('/api/admin/login',authLimit,(req,res)=>{if(typeof req.body.password!=='string'||!equal(hash(req.body.password),hash(process.env.ADMIN_PASSWORD)))return fail(res,401,'Invalid password');let exp=Date.now()+8*3600_000;res.cookie('exam_admin',sign(`${exp}:${randomBytes(16).toString('hex')}`),cookie('exam_admin','',8*3600_000));res.json({ok:true})});
app.post('/api/admin/logout',admin,(req,res)=>{res.clearCookie('exam_admin',{path:'/'});res.json({ok:true})});
app.get('/api/admin/state',admin,async(req,res)=>{let [e,qs,count]=await Promise.all([config(),Question.find().sort({_id:1}).lean(),Attempt.countDocuments()]);res.json({config:e,questions:qs,attemptCount:count,serverNow:new Date()})});
app.put('/api/admin/config',admin,async(req,res)=>{let old=await config();if(old?.open||await Attempt.countDocuments())return fail(res,409,'Settings locked while exam is open or attempts exist');let result=validateConfig(req.body);if(result.error)return fail(res,400,result.error);let e=await Exam.findOneAndUpdate({key:'one'},{$set:{...result.value,open:false}}, {upsert:true,new:true,runValidators:true});res.json({config:e})});
app.put('/api/admin/questions/:id',admin,async(req,res)=>{let e=await config();if(e?.open||await Attempt.countDocuments()>0)return fail(res,409,'Questions locked once the exam starts');let check=validateQuestion(req.body);if(check.error)return fail(res,400,check.error);let q;if(req.params.id==='new'){if(await Question.countDocuments()>=15)return fail(res,409,'Only 15 questions allowed');q=await Question.create(check.value)}else{if(!mongoose.isValidObjectId(req.params.id))return fail(res,400,'Invalid question');q=await Question.findByIdAndUpdate(req.params.id,check.value,{new:true,runValidators:true});if(!q)return fail(res,404,'Question not found')}res.json({question:q})});
app.delete('/api/admin/questions/:id',admin,async(req,res)=>{let e=await config();if(e?.open||await Attempt.countDocuments()>0)return fail(res,409,'Questions locked once the exam starts');await Question.findByIdAndDelete(req.params.id);res.json({ok:true})});
app.put('/api/admin/roster',admin,async(req,res)=>{let e=await config();if(e?.open||await Attempt.countDocuments())return fail(res,409,'Roster locked when exam is open or attempts exist');let r=parseRoster(req.body.text);if(r.error)return fail(res,400,r.error);await Exam.findOneAndUpdate({key:'one'},{$set:{roster:r.value}}, {upsert:true,new:true});res.json({count:r.value.length})});
app.post('/api/admin/open',admin,async(req,res)=>{let e=await config(), n=await Question.countDocuments();if(!e?.durationMinutes||n!==15)return fail(res,409,'Save settings and exactly 15 questions first');await Exam.updateOne({key:'one'},{$set:{open:true}});res.json({ok:true})});
app.post('/api/admin/close',admin,async(req,res)=>{await Exam.updateOne({key:'one'},{$set:{open:false}});res.json({ok:true})});
app.post('/api/join',joinLimit,async(req,res)=>{let e=await config();if(!e?.open)return fail(res,403,'Exam is not accepting new entries');let ident=normalizeIdentity(req.body);if(ident.error)return fail(res,400,ident.error);let qs=await Question.find().sort({_id:1}).lean();if(qs.length!==15)return fail(res,503,'Exam is not ready');if(!domainAllows(ident.value.collegeId,e.allowedDomains))return fail(res,403,'College ID must be an email address at '+e.allowedDomains.map(d=>'@'+d).join(' or '));if(!e.allowedDomains?.length && e.roster?.length && !e.roster.some(r=>r.roll===ident.value.roll && r.collegeId.toLowerCase()===ident.value.collegeId.toLowerCase()))return fail(res,403,'College ID and roll number are not on the allowed roster');let slot=await Exam.findOneAndUpdate({key:'one',open:true,admitted:{$lt:60}},{$inc:{admitted:1}},{new:true});if(!slot)return fail(res,403,'Exam capacity reached or closed');let token=randomBytes(32).toString('hex'),start=new Date();try{let a=await Attempt.create({...ident.value,tokenHash:hash(token),startedAt:start,deadlineAt:deadlineFor(start,e),questionSnapshot:qs.map(q=>({questionId:String(q._id),text:q.text,options:q.options,correct:q.correct}))});res.cookie('exam_student',sign(token),cookie('exam_student','',e.durationMinutes*60_000+3600_000));res.json({ok:true,attemptId:String(a._id)})}catch(err){await Exam.updateOne({key:'one'},{$inc:{admitted:-1}});if(err.code===11000)return fail(res,409,'This university roll number already started the exam. Ask the admin for help.');throw err}});
app.get('/api/student',student,async(req,res)=>{let a=await currentAttempt(req.attempt);res.json({name:a.name,startedAt:a.startedAt,deadlineAt:a.deadlineAt,serverNow:new Date(),submittedAt:a.submittedAt,submitReason:a.submitReason,score:a.submittedAt?a.score:undefined,violations:a.violations.length,answers:Object.fromEntries(a.answers||new Map()),questions:a.submittedAt?[]:a.questionSnapshot.map(({questionId,text,options})=>({id:questionId,text,options}))})});
app.put('/api/answer',student,async(req,res)=>{let a=await currentAttempt(req.attempt);if(a.submittedAt)return fail(res,409,'Exam already submitted');let q=a.questionSnapshot.find(q=>q.questionId===req.body.id);if(!q||!Number.isInteger(req.body.choice)||req.body.choice<0||req.body.choice>3)return fail(res,400,'Invalid answer');await Attempt.updateOne({_id:a._id,submittedAt:null},{$set:{[`answers.${q.questionId}`]:req.body.choice}});res.json({ok:true})});
app.post('/api/violation',student,async(req,res)=>{let a=await currentAttempt(req.attempt);if(a.submittedAt)return res.json({submitted:true,violations:a.violations.length});let kind=req.body.kind;if(!['tab-hidden','fullscreen-exit','window-blur'].includes(kind))return fail(res,400,'Invalid violation');let e=await config();await Attempt.updateOne({_id:a._id,submittedAt:null},{$push:{violations:{kind,at:new Date()}}});a=await Attempt.findById(a._id);if(a.violations.length>=e.maxViolations)a=await finalize(a,'violations');res.json({submitted:!!a.submittedAt,violations:a.violations.length,limit:e.maxViolations})});
app.post('/api/submit',student,async(req,res)=>{let a=await currentAttempt(req.attempt);a=await finalize(a,'student');res.json({ok:true,score:a.score})});
app.get('/api/admin/results',admin,async(req,res)=>{await finalizeExpired();let attempts=await Attempt.find().sort({startedAt:1}).lean();res.json({attempts:attempts.map(a=>({id:String(a._id),collegeId:a.collegeId,name:a.name,roll:a.roll,startedAt:a.startedAt,deadlineAt:a.deadlineAt,submittedAt:a.submittedAt,submitReason:a.submitReason,score:a.score,violations:a.violations}))})});
app.get('/api/admin/export',admin,async(req,res)=>{await finalizeExpired();let attempts=await Attempt.find().sort({startedAt:1}).lean();let headers=['college_id','name','roll_number','started_at','deadline_at','submitted_at','submit_reason','score','violations','question_number','question','selected_answer','correct_answer','is_correct'];let rows=[headers];for(let a of attempts){let answers=a.answers instanceof Map?Object.fromEntries(a.answers):Object.fromEntries(Object.entries(a.answers||{}));a.questionSnapshot.forEach((q,i)=>rows.push([a.collegeId,a.name,a.roll,a.startedAt,a.deadlineAt,a.submittedAt||'',a.submitReason||'',a.score??'',a.violations.map(v=>`${v.kind}@${new Date(v.at).toISOString()}`).join('; '),i+1,q.text,Number.isInteger(answers[q.questionId])?q.options[answers[q.questionId]]:'',q.options[q.correct],answers[q.questionId]===q.correct?'yes':'no']))}res.set('Content-Type','text/csv; charset=utf-8');res.set('Content-Disposition','attachment; filename="exam-response-sheets.csv"');res.send('\ufeff'+rows.map(r=>r.map(safeCsvCell).join(',')).join('\r\n'))});
app.use(express.static(path.join(baseDir,'public'),{maxAge:'5m'}));app.get('/admin',(req,res)=>res.sendFile(path.join(baseDir,'public','admin.html')));
app.use((err,req,res,next)=>{console.error(err);return fail(res,500,'Server error')});
const port=Number(process.env.PORT||3000);app.listen(port,()=>console.log(`Exam listening on ${port}`));
