import test from 'node:test';import assert from 'node:assert/strict';import {MongoMemoryServer} from 'mongodb-memory-server';import {spawn} from 'node:child_process';import {randomBytes} from 'node:crypto';
let db,server,origin,adminCookie,studentCookie,controller;
async function request(route,method='GET',body,cookie){let r=await fetch(origin+'/api'+route,{method,headers:{origin,'x-exam-request':'1','Content-Type':'application/json',...(cookie?{cookie}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,headers:r.headers,data:await r.json()}}
async function waitReady(){for(let i=0;i<50;i++){try{let r=await fetch(origin+'/api/public');if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('server did not start')}
test('full exam: admin, roster, 15 questions, join, answer, violation, CSV, identity gates',async()=>{
 db=await MongoMemoryServer.create();let port=30000+Math.floor(Math.random()*15000);origin=`http://127.0.0.1:${port}`;server=spawn(process.execPath,['server.js'],{env:{...process.env,MONGODB_URI:db.getUri('examtest'),ADMIN_PASSWORD:'strong-test-password',SESSION_SECRET:randomBytes(32).toString('hex'),PUBLIC_ORIGIN:origin,PORT:String(port)},stdio:['ignore','pipe','pipe']});let stderr='';server.stderr.on('data',x=>{stderr+=x});
 try{await waitReady();let p=await request('/join','POST',{collegeId:'Alice@SKIT.AC.IN',name:'Alice Test',roll:'A100'});assert.equal(p.status,403);let login=await request('/admin/login','POST',{password:'strong-test-password'});assert.equal(login.status,200,stderr);adminCookie=login.headers.get('set-cookie').split(';')[0];let noOrigin=await fetch(origin+'/api/admin/config',{method:'PUT',headers:{cookie:adminCookie,'Content-Type':'application/json'},body:JSON.stringify({title:'Test'})});assert.equal(noOrigin.status,403);
 let cfg=await request('/admin/config','PUT',{title:'Practice Quiz',durationMinutes:15,maxViolations:2,allowedDomains:['skit.ac.in']},adminCookie);assert.equal(cfg.status,200);let roster=await request('/admin/roster','PUT',{text:'C01,A100\nC02,B200'},adminCookie);assert.equal(roster.status,200);
 for(let i=0;i<15;i++){let r=await request('/admin/questions/new','PUT',{text:`Question ${i+1}?`,options:['One','Two','Three','Four'],correct:1,marks:i===6?3:1},adminCookie);assert.equal(r.status,200,JSON.stringify(r.data))}
 let opened=await request('/admin/open','POST',{},adminCookie);assert.equal(opened.status,200);for(let collegeId of ['bad@gmail.com','bad@sub.skit.ac.in','bad@skit.ac.in.evil.com','bad@evilskit.ac.in']){let wrong=await request('/join','POST',{collegeId,name:'Bad User',roll:'X100'});assert.equal(wrong.status,403)}
 let joined=await request('/join','POST',{collegeId:'Alice@SKIT.AC.IN',name:'Alice Test',roll:'A100'});assert.equal(joined.status,200,JSON.stringify(joined.data));studentCookie=joined.headers.get('set-cookie').split(';')[0];let duplicate=await request('/join','POST',{collegeId:'Alice@SKIT.AC.IN',name:'Alice Test',roll:'A100'});assert.equal(duplicate.status,409);
 let sameId=await request('/join','POST',{collegeId:'alice@skit.ac.in',name:'Other Test',roll:'DIFFERENT'});assert.equal(sameId.status,409);assert.match(sameId.data.error,/college ID/);let student=await request('/student','GET',undefined,studentCookie);assert.equal(student.data.questions.length,15);assert.ok(!JSON.stringify(student.data).includes('correct'));assert.equal(new Date(student.data.deadlineAt).getTime()-new Date(student.data.startedAt).getTime(),15*60_000);
 let a=await request('/answer','PUT',{id:student.data.questions[0].id,choice:1},studentCookie);assert.equal(a.status,200);await request('/answer','PUT',{id:student.data.questions[6].id,choice:1},studentCookie);let v1=await request('/violation','POST',{kind:'tab-hidden'},studentCookie);assert.equal(v1.data.submitted,false);let v2=await request('/violation','POST',{kind:'fullscreen-exit'},studentCookie);assert.equal(v2.data.submitted,true);let results=await request('/admin/results','GET',undefined,adminCookie);assert.equal(results.data.attempts[0].score,4);assert.equal(results.data.attempts[0].submitReason,'violations');assert.equal(results.data.attempts[0].violations.length,2);let exportR=await fetch(origin+'/api/admin/export',{headers:{cookie:adminCookie}});let csv=await exportR.text();assert.equal(csv.split('\r\n').length,16);assert.ok(csv.includes('Alice Test'));assert.equal(results.data.attempts[0].totalMarks,17);assert.ok(csv.includes('question_marks'));assert.match(csv.split('\r\n')[7],/"3","3","17"$/);let change=await request('/admin/config','PUT',{title:'Changed',durationMinutes:10,maxViolations:2},adminCookie);assert.equal(change.status,409);let closed=await request('/admin/close','POST',{},adminCookie);assert.equal(closed.status,200);let denied=await request('/join','POST',{collegeId:'C02',name:'Bob Test',roll:'B200'});assert.equal(denied.status,403);let reset=await request('/admin/reset-attempts','POST',{confirm:'no'},adminCookie);assert.equal(reset.status,400);reset=await request('/admin/reset-attempts','POST',{confirm:'DELETE ALL ATTEMPTS'},adminCookie);assert.equal(reset.data.attemptCount,0);let clean=await request('/admin/state','GET',undefined,adminCookie);assert.equal(clean.data.questions.length,15);assert.equal(clean.data.config.open,false);assert.equal(clean.data.config.admitted,0);assert.equal(clean.data.config.title,'Practice Quiz');
 }finally{server?.kill();await db?.stop()}
},{timeout:120000});
